// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fiudbwjegjhzyykbkoug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpdWRid2plZ2poenl5a2Jrb3VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NDc2NzIsImV4cCI6MjA2MjQyMzY3Mn0.oY6ozVURH9bhQ3yixumoFrhTne51RQhKJvgm-LF3CSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);