// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyzvkrucxdmckuuqedbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5enZrcnVjeGRtY2t1dXFlZGJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MjY5NjYsImV4cCI6MjA2MjUwMjk2Nn0.ppScFfk33knyWY57qUu4QcByR7DDvz2PHCm2QiW2Yvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);